# Generated by Django 2.0.1 on 2018-02-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_remove_contacttable_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacttable',
            name='note',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
