# Generated by Django 2.0.1 on 2018-02-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contacttable_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacttable',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contacttable',
            name='midName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contacttable',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
