# Generated by Django 2.0.1 on 2018-02-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20180201_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacttable',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
